name: Cypress CI Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress and Fix Permissions
        run: |
          npm install cypress --save-dev
          npx cypress install
          chmod +x node_modules/.bin/cypress

      - name: Run Cypress Tests on Live Server
        run: npx cypress run
        env:
          CYPRESS_baseUrl: "https://blue-aardvark-631260.hostingersite.com"